### ISSUE TITLE
on keyboard hide 

### ISSUE THREAD

**Issue by hatemragab** [drogel/keyboard_dismisser#7] opened 2021-04-27 00:24 UTC
this package does not work if the keyboard hide  it sill fouces  thanks

**Comment by drogel** [comment] 2021-04-27 06:24
Hi @hatemragab,

First of all thanks for using the package and for taking the time to open this issue. I have been taking a look at it and I would need more information on the exact conditions in which you observed that the package stopped working. I have built the example app from the package using the latest version and the app seems to work fine. You can take a look at the `main.dart` of this example app [here](https://github.com/drogel/keyboard_dismisser/blob/master/example/lib/main.dart). It might be useful for you, since it contains a code snippet for the typical use case for the package.

So I need to know more about the details of your implementation in order to help you with the issue. A minimal code sample that reproduces the issue you describe would be ideal for me to find out if there is something wrong with the package.

Thanks a lot!

**Comment by drogel** [comment] 2021-11-13 11:27
I am closing this issue, since no updates have been received, and no minimal reproducible example has been provided.

**Closed as completed by drogel** 2021-11-13 11:27 UTC
